### ISSUE TITLE
EdgeGPT V0.13.1 pypi push. EdgeGPT 最后一个版本未上传pypi

### ISSUE THREAD

**Issue by huwei901108** [acheong08/acheong08#4]
EdgeGPT V0.13.1 pypi push.
嗨，我注意到EdgeGPT archived 了，但是貌似最后一个版本V0.13.1没能成功自动push到pypi 上
目前最后版本0.12 是存在随机ip地址的问题的版本，V0.13.1貌似合入了能修复的patch
能否麻烦把最后一个版本V0.13.1 push到pypi 呢，谢谢

**Comment by acheong08** [comment]
谢谢告诉我
