### ISSUE TITLE
 I would like to make continuous EdgeGpt project 

### ISSUE THREAD

**Issue by Yorddyyorddy** [acheong08/acheong08#5]
as it has been great project but now no one is maintaining it ,and you got some problems I understand 
but I want to update the package with your little help , I am not familiar with reverse engineering so I need some guidelines on it , so I need you to give me your Telegram username or WhatsApp

**Comment by acheong08** [comment]
I have neither Telegram nor Whatsapp. It has been a long while since I've touched EdgeGPT and thus I have little to contribute. @xtekky might be of more help (He maintains a similar repository with 44.4k stars)

**Comment by Yorddyyorddy** [comment]
> I have neither Telegram nor Whatsapp. It has been a long while since I've touched EdgeGPT and thus I have little to contribute. @xtekky might be of more help (He maintains a similar repository with 44.4k stars)

Thanks i will look at it 

But i have a question i tried to inspect Bing while chat and the fetch have no any payload and it's just get request , is there something additional i have to do with inspect setting

**Comment by acheong08** [comment]
> is there something additional i have to do with inspect setting

Websocket

**Comment by Yorddyyorddy** [comment]
> > is there something additional i have to do with inspect setting
> 
> Websocket

oh got it.
and one more thing  how did you obtained the snme0 value does connected to the bard source 

also if you have any intermediate  or advanced  rereverse engineering course just link me

**Comment by acheong08** [comment]
>  and one more thing how did you obtained the snme0 value does connected to the bard source

I don't fully remember. Probably looking at the request then ctrl+f to find where it came from.

> also if you have any intermediate or advanced rereverse engineering course just link me

I've never taken any real courses. just read docs & google stuff

**Comment by Yorddyyorddy** [comment]
> > and one more thing how did you obtained the snme0 value does connected to the bard source
> 
> I don't fully remember. Probably looking at the request then ctrl+f to find where it came from.
> ok 
> > also if you have any intermediate or advanced rereverse engineering course just link me
> 
> I've never taken any real courses. just read docs & google stuff 
thanks ,I'll meet you as may things get hardy

**Comment by Yorddyyorddy** [comment]
I am back sir wishing you have been enjoying great days

How can i get an html page visible in elements tab during inspection with request 
I even tried requests-html but it only retrieve the source 

example https://www.ebooks-for-all.com/ebook-mobile-search-results.html?q=python
