### ISSUE TITLE
RevChatGPT V1

### ISSUE THREAD

**Issue by ttamoud** [acheong08/acheong08#6]
Hello,

First and foremost, I want to extend my deepest appreciation for the incredible work you've done. It has opened up so many possibilities for us, and I'm genuinely grateful.

I've been closely tracking the progress of your revChatGPT repository, with a particular interest in version 1, which I believe stands out impressively. However, I've noticed that bypass.churchless.tech has been inaccessible for some time, rendering it challenging to execute the program. While stats.churchless.tech does provide alternative URLs, it seems they might not be compatible with the arkose token system.

I've dedicated a good 48 hours trying to troubleshoot and resolve the issue on my own, but unfortunately, I haven't made much progress. If you could offer some guidance or pointers on what I should be looking into or what modifications might be required, I'd be profoundly appreciative. Alternatively, if you ever find a free moment, I'd be grateful if you could take a look at it.

Thank you once again for your remarkable contributions. I genuinely hold your work in high esteem.

A TRULY ARDENT ADMIROR OF YOUR WORK !!

**Comment by acheong08** [comment]
Hello,

As you can see on the repository pages, all my ChatGPT works have been archived and have been unmaintained for a while. The bypass server was working despite being completely unmaintained until about a week ago. Cloudflare has probably banned the IP address. Since I no longer maintained the server code, I shut down the server (which costed me about $200 over the course of its life due to bandwidth). The code for it has always been open source at https://github.com/acheong08/ChatGPTProxy if you wanted to run it for yourself but it might not work anymore due to new bot detection mechanisms by Cloudflare.

I strongly recommend https://github.com/linweiyuan/go-chatgpt-api which is maintained by a much more experienced developer but the documentation is in Chinese. You could ask ChatGPT to translate it.

**Comment by acheong08** [comment]
Regarding the arkose token, please join their telegram channel for more information. I don't remember the link as I lost my Telegram account.

**Comment by Ahmet-Dedeler** [comment]
Hey @ttamoud, I've been having the exact same dilemma, trying to run the v1, but no luck 😅 Tried setting up the https://github.com/acheong08/ChatGPTProxy as my own proxy on github codespaces, but that didn't work either. I might have not done the setup right but I'm not sure

The chinese library @acheong08 mentioned seems a bit confusing, were you able to set that up correctly or had any luck finding another solution? There doesn't seem to be any other projects in this regard. The revChatGPT v1 was amazing to test apps without having to use the official API, quite sad that it doesn't work anymore :(

Either way @acheong08 what you made was amazing so thanks a whole lot 😄 If anyone knows how to fix this please lmk!! would really appreciate any help!!

**Comment by ttamoud** [comment]
Hey @PrettyXD, i have found a way to make it work but i'm sure it wont be long until they take down this endpoint too.

Go to your revchatgpt folder, find the V1.py, replace every occurrence of "bypass.churchless.tech" with "ai.fakeopen.com/api/" that should fix it for the gpt 3.5.

Still working on the gpt4 problem, nothing at the moment.

**Comment by acheong08** [comment]
https://github.com/zhile-io/pandora/

^ This is the guy maintaining `ai.fakeopen.com`. I didn't recommend it at first because it isn't open source but afaik it has pretty good uptime.

**Comment by acheong08** [comment]
> Go to your revchatgpt folder, find the V1.py, replace every occurrence of "bypass.churchless.tech" with "ai.fakeopen.com/api/" that should fix it for the gpt 3.5.

No need for that. Just `export CHATGPT_BASE_URL=https://ai.fakeopen.com/api/`

In Python:
```py
os.environ["CHATGPT_BASE_URL"] = "https://ai.fakeopen.com/api/"
```

**Comment by ttamoud** [comment]
At the moment i couldn't find any other working endpoints.
Still no solution tho for the gpt-4, i found the arkose telegram but no success making it work, any leads to follow maybe ?

**Comment by acheong08** [comment]
Try https://github.com/noahcoolboy/funcaptcha/. It *might* work. Requires some work: create api, plug it into https://github.com/acheong08/ChatGPT/blob/9167b325addc7d3520987face684e8230bd62b46/src/revChatGPT/V1.py#L155-L231, etc.

First check if the arkose token passes the captcha before doing any real work

**Comment by acheong08** [comment]
One last resort if you're willing to spend some money is https://2captcha.com/. I can share an API key with $5 since I won't be using ChatGPT myself. I bought the credits thinking I was gonna use it but never did

**Comment by ttamoud** [comment]
I'm gonna try the funcaptcha first, if no success i will move to the paid solution, i'll keep you updated.

For the api key, i'll reach back to you if i need it, i'll buy it from you ofc.

Thanks again for the feedbacks

**Comment by Ahmet-Dedeler** [comment]
a bit of a late response but @ttamoud thank you very much for mentioning that endpoint, it works perfectly. regarding the captcha, i didnt have any problems at the moment.

btw before using the endpoint you mentioned I set up my own server using https://github.com/acheong08/ChatGPT-to-API and that worked too, but using the other library makes it easier for me so I'll be using that.

please let me know if you got funcaptcha to work or found any other solutions (although I didnt have any problems until now)

thanks a lot!

**Comment by ghbbeep** [comment]
Does anyone know any quick replacements for free.churchless.tech?
